apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: greetings.operator.example.com
spec:
  group: operator.example.com
  scope: Namespaced
  names:
    kind: Greeting
    plural: greetings
    singular: greeting
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              message:
                type: string
            required: ["message"]
